import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';

class AppIcon extends StatelessWidget {
  final IconData icon;
  final double? size;
  final Color? color;
  final String? semanticLabel;
  final TextDirection? textDirection;
  final List<Shadow>? shadows;
  final double? fill;
  final double? weight;
  final double? grade;
  final double? opticalSize;
  final bool? applyTextScaling;
  final BlendMode? blendMode;

  const AppIcon(
    this.icon, {
    super.key,
    this.size,
    this.color,
    this.semanticLabel,
    this.textDirection,
    this.shadows,
    this.fill,
    this.weight,
    this.grade,
    this.opticalSize,
    this.applyTextScaling,
    this.blendMode,
  });

  @override
  Widget build(BuildContext context) {
    final iconTheme = IconTheme.of(context);
    final effectiveSize = size ?? iconTheme.size ?? 24;
    final effectiveColor = color ?? iconTheme.color ?? Colors.black;

    Widget child = HugeIcon(
      icon: _AppHugeIconMap.resolve(icon),
      color: effectiveColor,
      size: effectiveSize,
      strokeWidth: _strokeWidth,
    );

    if (blendMode != null) {
      child = ColorFiltered(
        colorFilter: ColorFilter.mode(effectiveColor, blendMode!),
        child: child,
      );
    }

    if (semanticLabel == null) return child;

    return Semantics(
      label: semanticLabel,
      textDirection: textDirection,
      child: child,
    );
  }

  double get _strokeWidth {
    final requestedWeight = weight;
    if (requestedWeight == null) return 1.8;
    return (requestedWeight / 250).clamp(1.4, 2.4).toDouble();
  }
}

class _AppHugeIconMap {
  const _AppHugeIconMap._();

  static List<List<dynamic>> resolve(IconData icon) {
    return _icons[icon] ?? HugeIcons.strokeRoundedSquare;
  }

  static final Map<IconData, List<List<dynamic>>> _icons = {
    Icons.ac_unit: HugeIcons.strokeRoundedSnow,
    Icons.access_time: HugeIcons.strokeRoundedClock01,
    Icons.account_balance_wallet_outlined: HugeIcons.strokeRoundedWallet01,
    Icons.add: HugeIcons.strokeRoundedAdd01,
    Icons.add_business: HugeIcons.strokeRoundedBuilding03,
    Icons.add_circle_outline: HugeIcons.strokeRoundedAddCircle,
    Icons.add_photo_alternate_outlined: HugeIcons.strokeRoundedImageAdd01,
    Icons.add_rounded: HugeIcons.strokeRoundedAdd01,
    Icons.add_shopping_cart_rounded: HugeIcons.strokeRoundedShoppingCartAdd01,
    Icons.all_inclusive: HugeIcons.strokeRoundedInfinity01,
    Icons.analytics_outlined: HugeIcons.strokeRoundedAnalytics01,
    Icons.approval_outlined: HugeIcons.strokeRoundedDocumentValidation,
    Icons.apps_rounded: HugeIcons.strokeRoundedGrid,
    Icons.arrow_back: HugeIcons.strokeRoundedArrowLeft01,
    Icons.arrow_back_ios: HugeIcons.strokeRoundedArrowLeft01,
    Icons.arrow_back_rounded: HugeIcons.strokeRoundedArrowLeft01,
    Icons.arrow_downward_rounded: HugeIcons.strokeRoundedArrowDown01,
    Icons.arrow_drop_down: HugeIcons.strokeRoundedArrowDown01,
    Icons.arrow_drop_up: HugeIcons.strokeRoundedArrowUp01,
    Icons.arrow_forward_ios: HugeIcons.strokeRoundedArrowRight01,
    Icons.arrow_upward_rounded: HugeIcons.strokeRoundedArrowUp01,
    Icons.assessment: HugeIcons.strokeRoundedAnalytics01,
    Icons.assessment_outlined: HugeIcons.strokeRoundedAnalytics01,
    Icons.assignment_outlined: HugeIcons.strokeRoundedTask01,
    Icons.assignment_returned_outlined: HugeIcons.strokeRoundedReturnRequest,
    Icons.assignment_turned_in_outlined: HugeIcons.strokeRoundedTaskDone01,
    Icons.attach_file: HugeIcons.strokeRoundedAttachment01,
    Icons.attach_money: HugeIcons.strokeRoundedDollar01,
    Icons.attach_money_rounded: HugeIcons.strokeRoundedDollar01,
    Icons.auto_awesome: HugeIcons.strokeRoundedAiBeautify,
    Icons.auto_graph_rounded: HugeIcons.strokeRoundedChartIncrease,
    Icons.block: HugeIcons.strokeRoundedUnavailable,
    Icons.block_rounded: HugeIcons.strokeRoundedUnavailable,
    Icons.bluetooth: HugeIcons.strokeRoundedBluetooth,
    Icons.bolt: HugeIcons.strokeRoundedFlash,
    Icons.business: HugeIcons.strokeRoundedBuilding03,
    Icons.business_center: HugeIcons.strokeRoundedBriefcase01,
    Icons.business_outlined: HugeIcons.strokeRoundedBuilding03,
    Icons.cable: HugeIcons.strokeRoundedCableCar,
    Icons.cake_outlined: HugeIcons.strokeRoundedCakeSlice,
    Icons.calculate: HugeIcons.strokeRoundedCalculator,
    Icons.calculate_outlined: HugeIcons.strokeRoundedCalculator,
    Icons.calendar_month: HugeIcons.strokeRoundedCalendar03,
    Icons.calendar_today: HugeIcons.strokeRoundedCalendar03,
    Icons.calendar_today_outlined: HugeIcons.strokeRoundedCalendar03,
    Icons.call_made: HugeIcons.strokeRoundedArrowUpRight01,
    Icons.call_received: HugeIcons.strokeRoundedArrowDownLeft01,
    Icons.call_received_outlined: HugeIcons.strokeRoundedArrowDownLeft01,
    Icons.camera_alt: HugeIcons.strokeRoundedCamera01,
    Icons.camera_alt_outlined: HugeIcons.strokeRoundedCamera01,
    Icons.campaign_outlined: HugeIcons.strokeRoundedMegaphone01,
    Icons.cancel: HugeIcons.strokeRoundedCancel01,
    Icons.cancel_outlined: HugeIcons.strokeRoundedCancel01,
    Icons.cancel_rounded: HugeIcons.strokeRoundedCancel01,
    Icons.category: HugeIcons.strokeRoundedPackage,
    Icons.category_outlined: HugeIcons.strokeRoundedPackage,
    Icons.chat_bubble_outline: HugeIcons.strokeRoundedMessage01,
    Icons.check: HugeIcons.strokeRoundedTick01,
    Icons.check_circle: HugeIcons.strokeRoundedCheckmarkCircle01,
    Icons.check_circle_outline: HugeIcons.strokeRoundedCheckmarkCircle01,
    Icons.check_circle_outline_rounded:
        HugeIcons.strokeRoundedCheckmarkCircle01,
    Icons.check_circle_rounded: HugeIcons.strokeRoundedCheckmarkCircle01,
    Icons.chevron_right: HugeIcons.strokeRoundedArrowRight01,
    Icons.chevron_right_rounded: HugeIcons.strokeRoundedArrowRight01,
    Icons.circle: HugeIcons.strokeRoundedCircle,
    Icons.clear: HugeIcons.strokeRoundedCancel01,
    Icons.close: HugeIcons.strokeRoundedCancel01,
    Icons.close_rounded: HugeIcons.strokeRoundedCancel01,
    Icons.cloud: HugeIcons.strokeRoundedCloud,
    Icons.cloud_off: HugeIcons.strokeRoundedCloudOff,
    Icons.cloud_off_rounded: HugeIcons.strokeRoundedCloudOff,
    Icons.code: HugeIcons.strokeRoundedCode,
    Icons.code_off: HugeIcons.strokeRoundedCode,
    Icons.copy: HugeIcons.strokeRoundedCopy01,
    Icons.copy_rounded: HugeIcons.strokeRoundedCopy01,
    Icons.create: HugeIcons.strokeRoundedEdit02,
    Icons.credit_card_rounded: HugeIcons.strokeRoundedCreditCard,
    Icons.dark_mode_rounded: HugeIcons.strokeRoundedMoon02,
    Icons.date_range: HugeIcons.strokeRoundedCalendar04,
    Icons.delete: HugeIcons.strokeRoundedDelete02,
    Icons.delete_forever_outlined: HugeIcons.strokeRoundedDelete02,
    Icons.delete_outline: HugeIcons.strokeRoundedDelete02,
    Icons.delete_sweep: HugeIcons.strokeRoundedDelete02,
    Icons.delivery_dining: HugeIcons.strokeRoundedDeliveryTruck01,
    Icons.description: HugeIcons.strokeRoundedFile01,
    Icons.description_outlined: HugeIcons.strokeRoundedFile01,
    Icons.dns: HugeIcons.strokeRoundedServerStack01,
    Icons.dns_outlined: HugeIcons.strokeRoundedServerStack01,
    Icons.done_all: HugeIcons.strokeRoundedTickDouble01,
    Icons.done_all_outlined: HugeIcons.strokeRoundedTickDouble01,
    Icons.done_all_rounded: HugeIcons.strokeRoundedTickDouble01,
    Icons.download: HugeIcons.strokeRoundedDownload01,
    Icons.download_done_outlined: HugeIcons.strokeRoundedDownload01,
    Icons.download_rounded: HugeIcons.strokeRoundedDownload01,
    Icons.drag_handle_rounded: HugeIcons.strokeRoundedDragDropHorizontal,
    Icons.edit: HugeIcons.strokeRoundedEdit02,
    Icons.edit_note: HugeIcons.strokeRoundedNoteEdit,
    Icons.edit_note_outlined: HugeIcons.strokeRoundedNoteEdit,
    Icons.edit_note_rounded: HugeIcons.strokeRoundedNoteEdit,
    Icons.edit_outlined: HugeIcons.strokeRoundedEdit02,
    Icons.email: HugeIcons.strokeRoundedMail01,
    Icons.email_outlined: HugeIcons.strokeRoundedMail01,
    Icons.error: HugeIcons.strokeRoundedAlertCircle,
    Icons.error_outline: HugeIcons.strokeRoundedAlert02,
    Icons.error_outline_outlined: HugeIcons.strokeRoundedAlert02,
    Icons.error_outline_rounded: HugeIcons.strokeRoundedAlert02,
    Icons.event: HugeIcons.strokeRoundedCalendar03,
    Icons.event_busy_outlined: HugeIcons.strokeRoundedCalendarRemove01,
    Icons.exposure_minus_1: HugeIcons.strokeRoundedMinusSign,
    Icons.fact_check_outlined: HugeIcons.strokeRoundedTaskDone01,
    Icons.fastfood: HugeIcons.strokeRoundedHamburger01,
    Icons.feedback_outlined: HugeIcons.strokeRoundedMessageQuestion,
    Icons.filter_list: HugeIcons.strokeRoundedFilter,
    Icons.fingerprint: HugeIcons.strokeRoundedIdentityCard,
    Icons.flag: HugeIcons.strokeRoundedFlag01,
    Icons.flag_outlined: HugeIcons.strokeRoundedFlag01,
    Icons.flash_on: HugeIcons.strokeRoundedFlash,
    Icons.format_align_left: HugeIcons.strokeRoundedTextAlignLeft,
    Icons.format_bold: HugeIcons.strokeRoundedTextBold,
    Icons.format_italic: HugeIcons.strokeRoundedTextItalic,
    Icons.format_list_bulleted: HugeIcons.strokeRoundedListView,
    Icons.format_underlined: HugeIcons.strokeRoundedTextUnderline,
    Icons.grass: HugeIcons.strokeRoundedLeaf01,
    Icons.grid_view: HugeIcons.strokeRoundedGrid,
    Icons.group_outlined: HugeIcons.strokeRoundedUserMultiple02,
    Icons.groups: HugeIcons.strokeRoundedUserMultiple02,
    Icons.help_outline: HugeIcons.strokeRoundedHelpCircle,
    Icons.help_rounded: HugeIcons.strokeRoundedHelpCircle,
    Icons.history: HugeIcons.strokeRoundedTimeQuarterPass,
    Icons.hourglass_top_rounded: HugeIcons.strokeRoundedHourglass,
    Icons.image: HugeIcons.strokeRoundedImage01,
    Icons.inbox_outlined: HugeIcons.strokeRoundedInbox,
    Icons.inbox_rounded: HugeIcons.strokeRoundedInbox,
    Icons.info: HugeIcons.strokeRoundedInformationCircle,
    Icons.info_outline: HugeIcons.strokeRoundedInformationCircle,
    Icons.info_outline_rounded: HugeIcons.strokeRoundedInformationCircle,
    Icons.insert_drive_file: HugeIcons.strokeRoundedFile01,
    Icons.inventory: HugeIcons.strokeRoundedPackage,
    Icons.inventory_2: HugeIcons.strokeRoundedPackage02,
    Icons.inventory_2_outlined: HugeIcons.strokeRoundedPackage02,
    Icons.inventory_outlined: HugeIcons.strokeRoundedPackage,
    Icons.keyboard_arrow_down: HugeIcons.strokeRoundedArrowDown01,
    Icons.keyboard_arrow_down_rounded: HugeIcons.strokeRoundedArrowDown01,
    Icons.keyboard_arrow_right_rounded: HugeIcons.strokeRoundedArrowRight01,
    Icons.keyboard_arrow_up: HugeIcons.strokeRoundedArrowUp01,
    Icons.label: HugeIcons.strokeRoundedLabel,
    Icons.layers_outlined: HugeIcons.strokeRoundedLayers01,
    Icons.light_mode_rounded: HugeIcons.strokeRoundedSun02,
    Icons.lightbulb: HugeIcons.strokeRoundedIdea01,
    Icons.lightbulb_outline: HugeIcons.strokeRoundedIdea01,
    Icons.link: HugeIcons.strokeRoundedLink01,
    Icons.local_shipping: HugeIcons.strokeRoundedTruck,
    Icons.local_shipping_outlined: HugeIcons.strokeRoundedTruck,
    Icons.location_city_outlined: HugeIcons.strokeRoundedBuilding03,
    Icons.location_city_rounded: HugeIcons.strokeRoundedBuilding03,
    Icons.location_on: HugeIcons.strokeRoundedLocation01,
    Icons.location_on_outlined: HugeIcons.strokeRoundedLocation01,
    Icons.lock: HugeIcons.strokeRoundedLock,
    Icons.lock_open_outlined: HugeIcons.strokeRoundedCircleUnlock01,
    Icons.lock_outline: HugeIcons.strokeRoundedLock,
    Icons.lock_outline_rounded: HugeIcons.strokeRoundedLock,
    Icons.logout_rounded: HugeIcons.strokeRoundedLogout01,
    Icons.map: HugeIcons.strokeRoundedMaps,
    Icons.menu: HugeIcons.strokeRoundedMenu01,
    Icons.menu_rounded: HugeIcons.strokeRoundedMenu01,
    Icons.minimize_rounded: HugeIcons.strokeRoundedMinusSign,
    Icons.money_off_csred_outlined: HugeIcons.strokeRoundedMoneyRemove01,
    Icons.money_off_outlined: HugeIcons.strokeRoundedMoneyRemove01,
    Icons.more_vert: HugeIcons.strokeRoundedMoreVertical,
    Icons.more_vert_rounded: HugeIcons.strokeRoundedMoreVertical,
    Icons.nights_stay: HugeIcons.strokeRoundedMoon02,
    Icons.north_east_rounded: HugeIcons.strokeRoundedArrowUpRight01,
    Icons.note: HugeIcons.strokeRoundedNote,
    Icons.note_alt: HugeIcons.strokeRoundedNote01,
    Icons.note_alt_outlined: HugeIcons.strokeRoundedNote01,
    Icons.note_outlined: HugeIcons.strokeRoundedNote,
    Icons.notes_outlined: HugeIcons.strokeRoundedNote,
    Icons.notifications_active: HugeIcons.strokeRoundedNotification01,
    Icons.notifications_active_outlined: HugeIcons.strokeRoundedNotification01,
    Icons.notifications_none_rounded: HugeIcons.strokeRoundedNotification01,
    Icons.notifications_off: HugeIcons.strokeRoundedNotificationOff01,
    Icons.notifications_off_outlined: HugeIcons.strokeRoundedNotificationOff01,
    Icons.notifications_outlined: HugeIcons.strokeRoundedNotification01,
    Icons.open_in_new: HugeIcons.strokeRoundedArrowUpRight01,
    Icons.outdoor_grill_rounded: HugeIcons.strokeRoundedBbqGrill,
    Icons.palette_outlined: HugeIcons.strokeRoundedPaintBrush02,
    Icons.pause_circle_outline: HugeIcons.strokeRoundedPauseCircle,
    Icons.payment: HugeIcons.strokeRoundedPayment01,
    Icons.payments: HugeIcons.strokeRoundedMoney03,
    Icons.payments_outlined: HugeIcons.strokeRoundedMoney03,
    Icons.pending: HugeIcons.strokeRoundedClock01,
    Icons.pending_actions_outlined: HugeIcons.strokeRoundedTaskDaily01,
    Icons.pending_actions_rounded: HugeIcons.strokeRoundedTaskDaily01,
    Icons.pending_outlined: HugeIcons.strokeRoundedClock01,
    Icons.people: HugeIcons.strokeRoundedUserMultiple02,
    Icons.people_alt_outlined: HugeIcons.strokeRoundedUserMultiple02,
    Icons.people_alt_rounded: HugeIcons.strokeRoundedUserMultiple02,
    Icons.people_outline: HugeIcons.strokeRoundedUserMultiple02,
    Icons.person: HugeIcons.strokeRoundedUser,
    Icons.person_2_outlined: HugeIcons.strokeRoundedUser,
    Icons.person_add_outlined: HugeIcons.strokeRoundedUserAdd01,
    Icons.person_outline: HugeIcons.strokeRoundedUser,
    Icons.person_outline_rounded: HugeIcons.strokeRoundedUser,
    Icons.phone: HugeIcons.strokeRoundedCall02,
    Icons.phone_outlined: HugeIcons.strokeRoundedCall02,
    Icons.photo_library: HugeIcons.strokeRoundedImage01,
    Icons.pie_chart: HugeIcons.strokeRoundedPieChart,
    Icons.place: HugeIcons.strokeRoundedLocation01,
    Icons.play_circle_filled: HugeIcons.strokeRoundedPlayCircle,
    Icons.point_of_sale_outlined: HugeIcons.strokeRoundedCashier02,
    Icons.precision_manufacturing_outlined: HugeIcons.strokeRoundedFactory,
    Icons.print: HugeIcons.strokeRoundedPrinter,
    Icons.print_disabled: HugeIcons.strokeRoundedPrinterOff,
    Icons.print_outlined: HugeIcons.strokeRoundedPrinter,
    Icons.priority_high: HugeIcons.strokeRoundedAlert02,
    Icons.public: HugeIcons.strokeRoundedGlobe02,
    Icons.public_rounded: HugeIcons.strokeRoundedGlobe02,
    Icons.push_pin: HugeIcons.strokeRoundedPin,
    Icons.push_pin_outlined: HugeIcons.strokeRoundedPin,
    Icons.qr_code: HugeIcons.strokeRoundedQrCode,
    Icons.qr_code_2: HugeIcons.strokeRoundedQrCode,
    Icons.qr_code_2_outlined: HugeIcons.strokeRoundedQrCode,
    Icons.queue_outlined: HugeIcons.strokeRoundedAddToList,
    Icons.queue_rounded: HugeIcons.strokeRoundedAddToList,
    Icons.radar: HugeIcons.strokeRoundedRadar01,
    Icons.radio_button_checked_rounded: HugeIcons.strokeRoundedRadioButton,
    Icons.radio_button_off_rounded: HugeIcons.strokeRoundedCircle,
    Icons.receipt: HugeIcons.strokeRoundedReceiptDollar,
    Icons.receipt_long: HugeIcons.strokeRoundedInvoice03,
    Icons.receipt_long_outlined: HugeIcons.strokeRoundedInvoice03,
    Icons.receipt_long_rounded: HugeIcons.strokeRoundedInvoice03,
    Icons.receipt_outlined: HugeIcons.strokeRoundedReceiptDollar,
    Icons.refresh: HugeIcons.strokeRoundedRefresh,
    Icons.refresh_rounded: HugeIcons.strokeRoundedRefresh,
    Icons.remove: HugeIcons.strokeRoundedMinusSign,
    Icons.remove_circle_outline: HugeIcons.strokeRoundedRemoveCircle,
    Icons.remove_rounded: HugeIcons.strokeRoundedMinusSign,
    Icons.remove_shopping_cart: HugeIcons.strokeRoundedShoppingCartRemove01,
    Icons.repeat: HugeIcons.strokeRoundedRepeat,
    Icons.reply: HugeIcons.strokeRoundedMessageCircleReply,
    Icons.restaurant: HugeIcons.strokeRoundedRestaurant01,
    Icons.restaurant_menu: HugeIcons.strokeRoundedRestaurant02,
    Icons.restaurant_menu_rounded: HugeIcons.strokeRoundedRestaurant02,
    Icons.restaurant_outlined: HugeIcons.strokeRoundedRestaurant01,
    Icons.restaurant_rounded: HugeIcons.strokeRoundedRestaurant01,
    Icons.reviews_outlined: HugeIcons.strokeRoundedStar,
    Icons.room_service_outlined: HugeIcons.strokeRoundedServingFood,
    Icons.save: HugeIcons.strokeRoundedFloppyDisk,
    Icons.scale: HugeIcons.strokeRoundedWeightScale,
    Icons.scale_outlined: HugeIcons.strokeRoundedWeightScale,
    Icons.schedule: HugeIcons.strokeRoundedClock01,
    Icons.schedule_outlined: HugeIcons.strokeRoundedClock01,
    Icons.schedule_rounded: HugeIcons.strokeRoundedClock01,
    Icons.science_outlined: HugeIcons.strokeRoundedTestTube01,
    Icons.search: HugeIcons.strokeRoundedSearch01,
    Icons.search_off: HugeIcons.strokeRoundedSearchRemove,
    Icons.search_rounded: HugeIcons.strokeRoundedSearch01,
    Icons.send: HugeIcons.strokeRoundedSent,
    Icons.send_outlined: HugeIcons.strokeRoundedSent,
    Icons.settings: HugeIcons.strokeRoundedSettings02,
    Icons.settings_outlined: HugeIcons.strokeRoundedSettings02,
    Icons.share_outlined: HugeIcons.strokeRoundedShare01,
    Icons.shield_outlined: HugeIcons.strokeRoundedShield01,
    Icons.shopping_bag: HugeIcons.strokeRoundedShoppingBag01,
    Icons.shopping_bag_outlined: HugeIcons.strokeRoundedShoppingBag01,
    Icons.shopping_basket: HugeIcons.strokeRoundedShoppingBasket01,
    Icons.shopping_basket_outlined: HugeIcons.strokeRoundedShoppingBasket01,
    Icons.shopping_cart: HugeIcons.strokeRoundedShoppingCart02,
    Icons.shopping_cart_outlined: HugeIcons.strokeRoundedShoppingCart02,
    Icons.show_chart: HugeIcons.strokeRoundedChartIncrease,
    Icons.sms_outlined: HugeIcons.strokeRoundedMessage01,
    Icons.soup_kitchen_outlined: HugeIcons.strokeRoundedChefHat,
    Icons.south_west_rounded: HugeIcons.strokeRoundedArrowDownLeft01,
    Icons.speed: HugeIcons.strokeRoundedSpeedTrain01,
    Icons.star: HugeIcons.strokeRoundedStar,
    Icons.star_border: HugeIcons.strokeRoundedStarOff,
    Icons.star_rate: HugeIcons.strokeRoundedStar,
    Icons.stars: HugeIcons.strokeRoundedStar,
    Icons.sticky_note_2_outlined: HugeIcons.strokeRoundedNote,
    Icons.storage: HugeIcons.strokeRoundedDatabase,
    Icons.store: HugeIcons.strokeRoundedStore01,
    Icons.store_outlined: HugeIcons.strokeRoundedStore01,
    Icons.storefront_rounded: HugeIcons.strokeRoundedStore01,
    Icons.subject_outlined: HugeIcons.strokeRoundedTextAlignLeft,
    Icons.support_agent: HugeIcons.strokeRoundedCustomerSupport,
    Icons.swap_horiz_rounded: HugeIcons.strokeRoundedArrowLeftRight,
    Icons.sync: HugeIcons.strokeRoundedReload,
    Icons.table_chart: HugeIcons.strokeRoundedTable,
    Icons.table_restaurant: HugeIcons.strokeRoundedTableRound,
    Icons.table_restaurant_outlined: HugeIcons.strokeRoundedTableRound,
    Icons.table_restaurant_rounded: HugeIcons.strokeRoundedTableRound,
    Icons.tag: HugeIcons.strokeRoundedTags,
    Icons.task_alt: HugeIcons.strokeRoundedTaskDone01,
    Icons.task_alt_outlined: HugeIcons.strokeRoundedTaskDone01,
    Icons.timer_off: HugeIcons.strokeRoundedClock04,
    Icons.timer_off_rounded: HugeIcons.strokeRoundedClock04,
    Icons.track_changes: HugeIcons.strokeRoundedTarget01,
    Icons.trending_down: HugeIcons.strokeRoundedChartDecrease,
    Icons.trending_up: HugeIcons.strokeRoundedChartIncrease,
    Icons.tune: HugeIcons.strokeRoundedFilterHorizontal,
    Icons.tune_rounded: HugeIcons.strokeRoundedFilterHorizontal,
    Icons.update: HugeIcons.strokeRoundedRefresh,
    Icons.usb: HugeIcons.strokeRoundedUsb,
    Icons.verified: HugeIcons.strokeRoundedCheckmarkBadge01,
    Icons.verified_outlined: HugeIcons.strokeRoundedCheckmarkBadge01,
    Icons.verified_rounded: HugeIcons.strokeRoundedCheckmarkBadge01,
    Icons.verified_user_outlined: HugeIcons.strokeRoundedShield01,
    Icons.visibility: HugeIcons.strokeRoundedView,
    Icons.visibility_off_outlined: HugeIcons.strokeRoundedViewOff,
    Icons.visibility_outlined: HugeIcons.strokeRoundedView,
    Icons.warning: HugeIcons.strokeRoundedAlert02,
    Icons.warning_amber: HugeIcons.strokeRoundedAlert02,
    Icons.warning_amber_rounded: HugeIcons.strokeRoundedAlert02,
    Icons.warning_outlined: HugeIcons.strokeRoundedAlert02,
    Icons.warning_rounded: HugeIcons.strokeRoundedAlert02,
    Icons.water_drop: HugeIcons.strokeRoundedWaterfallDown01,
    Icons.wb_cloudy: HugeIcons.strokeRoundedCloud,
    Icons.wb_sunny: HugeIcons.strokeRoundedSun02,
    Icons.wb_twilight: HugeIcons.strokeRoundedSunset,
    Icons.wifi: HugeIcons.strokeRoundedWifi01,
    Icons.wifi_off: HugeIcons.strokeRoundedWifiOff01,
    Icons.wifi_off_rounded: HugeIcons.strokeRoundedWifiOff01,
    Icons.workspace_premium: HugeIcons.strokeRoundedAward01,
  };
}
